#-Enviroment--Variables----------
export EDITOR=nvim
export CONFIG=~/.config/
export PATH="$HOME/.config/npm-global/bin:$PATH"

#-Path to oh-my-zsh
export ZSH=$HOME/.oh-my-zsh

#-Theme
POWERLEVEL9k_MODE='awesome-fontconfig'
ZSH_THEME="pygmalion"

#-Plugins
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
fi

#-Aliases------------------

#Config Alias

alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzshconf="$EDITOR ~/.oh-my-zsh"
alias i3config="$EDITOR ~/.config/i3/config"
alias polyconf="$EDITOR ~/.config/polybar/config"
alias xresources="$EDITOR ~/.Xresources"

#alias to abreviate systemctl commands

alias poweroff="systemctl poweroff"
alias shutdow="poweroff"
alias reboot="systemctl reboot"
alias syssuspend="systemctl suspend"

#pacman / pacuar alias

alias paci="sudo pacman -S"
alias pacu="sudo pacman -Syu"
alias pacfind="sudo pacman -Ss"

#other random aliases
alias ls="exa"
alias demacs="emacsclient -nc -s instance"

alias hotspot="echo -e \"CIA Surveillance Truck #19\na123456789\" | sudo ~/create_ap/create_ap wlp3s0 enp0s20u2u3 "
alias cprepo="sh ~/Projects/cat_configs.sh"

alias lock="betterlockscreen -l blur; amixer -D pulse sset Master mute"
