# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

#----Enviroment--Variables----------

export NOUGAT_SCREENSHOT_DIRECTORY="$HOME/screenshots"
export EDITOR=nvim
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

POWERLEVEL9k_MODE='awesome-fontconfig'
ZSH_THEME="pygmalion"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

#-----Plugins
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

#-------------Aliases------------------
#
#Config Alias
#
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzshconf="$EDITOR ~/.oh-my-zsh"
alias i3config="$EDITOR ~/.config/i3/config"
alias polyconf="$EDITOR ~/.config/polybar/config"
alias xresources="$EDITOR ~/.Xresources"

#alias to abreviate systemctl commands

alias poweroff="systemctl poweroff"
alias shutdow="poweroff"
alias reboot="systemctl reboot"
alias syssuspend="systemctl suspend"

#pacman /  pacuar alias

alias paci="sudo pacman -S"
alias pacu="sudo pacman -Syu"
alias pacfind="sudo pacman -Ss"
alias aur="pacaur -S"
